name: quest_tracker
description: "A new Flutter project."

publish_to: 'none'

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Local embedded DB - pure Dart (no codegen)
  sembast: ^3.1.0
  path_provider: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
